export const wordlist = [
  { word: "Enigma", tip: "Desafio" },
  { word: "Mistério", tip: "Intriga" },
  { word: "Relógio", tip: "Ponteiros" },
  { word: "Esconde", tip: "Revela" },
  { word: "Máquina", tip: "Engrenagem" },
  { word: "Floresta", tip: "Vegetação" },
  { word: "Monstro", tip: "Assustador" },
  { word: "Violino", tip: "Cordas" },
  { word: "Labirinto", tip: "Perdido" },
  { word: "Terremoto", tip: "Abalo" },
  { word: "Ruínas", tip: "Antigas" },
  { word: "Coragem", tip: "Valente" },
  { word: "Quebrado", tip: "Frágil" },
  { word: "Ventania", tip: "Tornado" },
  { word: "Telescópio", tip: "Estrelas" },
  { word: "Eternidade", tip: "Infinito" },
  { word: "Camuflagem", tip: "Esconder" },
  { word: "Abdução", tip: "Extraterrestre" },
  { word: "Palimpsesto", tip: "Manuscrito" },
  { word: "Criptografia", tip: "Codificado" },
  { word: "Nevoeiro", tip: "Visibilidade" },
  { word: "Insondável", tip: "Profundo" },
  { word: "Espectral", tip: "Fantasma" },
  { word: "Conundrum", tip: "Enigma" },
  { word: "Alquimista", tip: "Transformação" },
  { word: "Nebulosa", tip: "Espacial" },
  { word: "Xerife", tip: "Oeste" },
  { word: "Resplendor", tip: "Brilho" },
  { word: "Abissal", tip: "Profundidade" },
  { word: "Solitário", tip: "Isolamento" },
  { word: "Paradigma", tip: "Modelo" },
  { word: "Serenidade", tip: "Tranquilidade" },
  { word: "Desespero", tip: "Angústia" },
  { word: "Intrincado", tip: "Complexo" },
  { word: "Cifra", tip: "Segredo" },
  { word: "Enferrujado", tip: "Oxidação" },
  { word: "Macabro", tip: "Assustador" },
  { word: "Revelação", tip: "Descoberta" },
  { word: "Cenário", tip: "Pintura" },
  { word: "Chiaroscuro", tip: "Contraste" },
  { word: "Monólito", tip: "Pedra" },
  { word: "Intrigante", tip: "Fascinante" },
  { word: "Espiríto", tip: "Sobrenatural" },
  { word: "Colossal", tip: "Gigante" },
  { word: "Sonâmbulo", tip: "Sono" },
  { word: "Mágico", tip: "Ilusão" },
  { word: "Abismo", tip: "Profundo" },
  { word: "Complexo", tip: "Intrigante" },
  { word: "Aparição", tip: "Fantasma" },
  { word: "Peculiar", tip: "Estranho" },
  { word: "Cataclismo", tip: "Desastre" },
  { word: "Serpentina", tip: "Curva" },
  { word: "Reliquia", tip: "Antiga" },
  { word: "Catacumba", tip: "Túmulo" },
  { word: "Sinistro", tip: "Arrepiante" },
  { word: "Anacronismo", tip: "Desatualizado" },
  { word: "Metamorfose", tip: "Transformação" },
  { word: "Desvendar", tip: "Descobrir" },
  { word: "Alquimia", tip: "Transformação" },
  { word: "Profético", tip: "Previsão" },
  { word: "Sarcófago", tip: "Túmulo" },
  { word: "Insólito", tip: "Estranho" },
  { word: "Esfinge", tip: "Quebra-cabeça" },
  { word: "Catastrofismo", tip: "Desastre" },
  { word: "Espetacular", tip: "Surpreendente" },
  { word: "Paradoxo", tip: "Contradição" },
  { word: "Magnífico", tip: "Impressionante" },
  { word: "Esfumado", tip: "Indefinido" },
  { word: "Nebuloso", tip: "Confuso" },
  { word: "Sideral", tip: "Espaço" },
  { word: "Imprevisível", tip: "Incerto" },
  { word: "Precipício", tip: "Abismo" },
  { word: "Luminoso", tip: "Brilhante" },
  { word: "Obscuro", tip: "Misterioso" },
  { word: "Reminiscência", tip: "Lembrança" },
  { word: "Desafiador", tip: "Difícil" },
  { word: "Anagrama", tip: "Palavras" },
  { word: "Deslumbrante", tip: "Impressionante" },
  { word: "Retumbante", tip: "Alto" },
  { word: "Profundo", tip: "Insondável" },
  { word: "Sobrenatural", tip: "Paranormal" },
  { word: "Desconcertante", tip: "Desorientador" },
  { word: "Criptograma", tip: "Código" },
  { word: "Oculto", tip: "Escondido" },
  { word: "Inefável", tip: "Indescritível" },
  { word: "Poltergeist", tip: "Assombração" },
];

// const noRepeatedWordlist = wordlist.filter((item, index) => {
//   if (index === 0) return true

//   const previousWordlist = wordlist.slice(0, index)

//   for (let i of previousWordlist) {
//     if (item.word === i.word) {
//       return false
//     }
//   }

//   return true
// })

// console.log(noRepeatedWordlist)

                                                                                    